import Head from 'next/head'
import Header from '../components/header/header'
import Section01 from '../components/section01'
import Section02 from '../components/section02'
import Section03 from '../components/section03'
import Section04 from '../components/section04'
import Footer from '../components/footer/footer'
import BackToTop from '../components/backToTop/backToTop'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Haikai - Moda e Estilo</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Section01 />
      <Section02 />
      <Section03 />
      <Section04 />
      <Footer />
      <BackToTop />
    </div>
  )
}
